### PR TITLE
Fix #780: don't crash if a queued call flow is invalid

### LINKED ISSUE #780: Queued calls are not being picked up by broker
On verboice.instedd.org, there are 18 legacy calls that are not picked up by the broker.

Note that when the broker starts, the scheduler does load them and dispatches them to the appropriate channel queues, but then they are lost from the queues. Review why they are being lost.

### PR DESCRIPTION
**Pull request by ggiraldez**
Improve handling of an invalid flow in a queued call, catching exceptions and
yielding an undefined flow to be later handled appropriately. Previously,
`twiml:parse/1` would crash terminating the `channel_queue` process. This would
lead to outstanding queued calls in the database and inability to continue
processing any other queued calls in the channel.

### CODE REVIEW

File: broker/src/session/session.erl [hunk 1]
```diff
@@ -173,50 +173,33 @@ ready({dial, _, _, QueuedCall = #queued_call{address = undefined}}, _From, State
...
-      };
-
-    Session ->
-      CallLog = Session#session.call_log,
-      Session#session{queued_call = QueuedCall, address = QueuedCall#queued_call.address}
-  end,
+  NewSession = #session{call_log = CallLog, flow = Flow} = prepare_session(QueuedCall, Channel, State),
 
-  % Don't the started_at if we are resuming an existing session
+  %% Don't set the started_at if we are resuming an existing session
```
Comment (spalladino) [inline broker/src/session/session.erl]: I had to google about the double `%%`, good catch
http://www.erlang.se/doc/programming_rules.shtml#HDR36

Comment (ggiraldez) [inline broker/src/session/session.erl]: Heh, that's all Emacs (or rather erlang-mode) merit which kept indenting the line to the far right.
