### PR TITLE
Automatically disable SIP channels if registration fails repeatedly

### LINKED ISSUE #782: Automatically disable channels if invalid auth
Currently on verboice.instedd.org there are more invalid than valid channels registered. This causes an extra load on asterisk, which could be avoided.

If a channel repeatedly fails registration, then disable it automatically, including a notice for the user indicating that it was disabled because of that.

Depends on #776

### PR DESCRIPTION
**Pull request by ggiraldez**
Closes #782

(Builds upon PR #792)

On each `check_status` (every 30 seconds), increment a counter if the channel
registration failed. If this value exceeds a threshold, disable the channel and
rewrite the configuration so that the disabled channel is not written to the
config file. Counts are reset if the registration succeeds or the configuration
is re-written.

NB: Asterisk will stop registration attempts if it receives a 401/403 from the
registration server. A reload (executed every 2 minutes) will force it to try
again.

### CODE REVIEW

File: broker/src/asterisk/asterisk_channel_srv.erl [hunk 1]
```diff
@@ -108,7 +121,8 @@ handle_cast(regenerate_config, State = #state{config_job_state = JobState}) ->
         ami_client:sip_reload(),
         gen_server:cast(?MODULE, {set_channels, ChannelIndex, RegistryIndex})
       end),
-      State#state{config_job_state = working};
+      % reset the count of registration failures
+      State#state{config_job_state = working, registration_failures = dict:new()};
```
Comment (ggiraldez) [inline broker/src/asterisk/asterisk_channel_srv.erl]: That would be ideal, but implies a lot more state needs to be kept somewhere. `updated_at` for each channel at the very least. Implementation shouldn't be very difficult.

File: broker/src/asterisk/asterisk_channel_srv.erl [hunk 2]
```diff
@@ -124,9 +138,24 @@ handle_cast({set_channels, ChannelIndex, RegistryIndex}, State = #state{config_j
...
-  {noreply, State#state{channel_status = Status, status_job_state = idle}};
+
+  % increment the registration failures
+  {NewRegFailures, DisableChannels} = update_registration_failures(Status, RegFailures),
+  if
+    length(DisableChannels) > 0 ->
+      % disable channels that have excedeed the number of failed status checks
+      lists:foreach(fun(ChannelId) ->
+                        channel:disable_by_id(ChannelId)
+                    end, DisableChannels),
```
Comment (ggiraldez) [inline broker/src/asterisk/asterisk_channel_srv.erl]: That could work. I was (sort of) mirroring the Ruby implementation.

Comment (ggiraldez) [inline broker/src/asterisk/asterisk_channel_srv.erl]: Two things changed my mind about this:

- I think it's a good idea to generate a log line for each disabled channel (for easier tracking)
- Automatic channel disabling shouldn't happen all that too often and it should only affect a small number of channels, due to the incremental nature of the procedure

I added a `channel:disable_by_ids/1` and moved the `lists:foreach/2` call over there though.
